version: '3'

services: 

    app:
        build: .docker/app
        depends_on: 
            - mysql
            - redis
        container_name: app
        volumes: 
            - ./Data/laravel:/var/www
        networks: 
            - app-network
        entrypoint: dockerize --wait tcp://mysql:3306 -timeout 40s .docker/app/entrypoint.sh

    nginx:
        build: .docker/nginx
        container_name: nginx
        restart: always
        tty: true
        ports: 
            - "80:80"
        volumes: 
            - ./Data/laravel:/var/www
        networks: 
            - app-network
        depends_on: 
            - app

    redis:
        image: redis:alpine
        expose: 
            - 6379
        networks: 
            - app-network
    
    mysql:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: mysql
        restart: always
        tty: true
        ports: 
            - "3306:3306"
        networks: 
            - app-network
        environment: 
            - MYSQL_DATABASE=laravel
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
        volumes: 
            - ./Data/database:/var/lib/mysql

networks:
    app-network:
        driver: bridge
