apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-nginx
spec:
    replicas: 1
    selector:
      matchLabels:
        app: web-nginx
    template:
        metadata:
            labels:
                app: web-nginx
        spec:
            containers:
                - name: nginx
                  image: nginx:1.15.0-alpine
                  ports:
                    - containerPort: 80                
                  volumeMounts:
                     - mountPath: /usr/share/nginx/html
                       name: index-html            
            volumes:
                 - name: index-html
                   configMap:
                     name: nginx-conf
                     items:
                         - key: index.html
                           path: index.html
