apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-server
spec:
    replicas: 1
    selector:
      matchLabels:
        app: mysql-server
        tier: db
    template:
        metadata:
            labels:
                app: mysql-server
                tier: db
        spec:
            containers:
                - name: mysql-server
                  image: mysql:5.7
                  args:
                    - "--ignore-db-dir=lost+found"
                  env:
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: mysql-pass
                          key: password
                  ports:
                    - containerPort: 3306
                  volumeMounts:
                    - mountPath: /var/ib/mysql
                      name: mysql-persistent-storage

            volumes:
                - name: mysql-persistent-storage
                  persistentVolumeClaim:
                    claimName: mysql-pv-claim