steps:
  - id: "Rodando testes"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "."]
    env: ["GOPATH=."]
    dir: "./src"

  - id: "Executando o script"
    name: "gcr.io/cloud-builders/go"
    args: ["run", "."]
    env: ["GOPATH=."]
    dir: "./src"